
package OdevClassPaketi;

import java.awt.Desktop;
import java.awt.List;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;



public class gui1 extends javax.swing.JFrame {
    String dosya_yolu = "C:\\Users\\husey\\Documents\\NetBeansProjects\\OtomataProjesi";
    
    

    /**
     * Creates new form Test
     */
    public gui1() {
        initComponents();
        setLocationRelativeTo(null);  //programın ekranın ortasında başlamasını sağlayan metod
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        regex_alani = new javax.swing.JTextField();
        pars_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        infix_alani = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nfa_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nfa_alani = new javax.swing.JTextArea();
        dosya_yolu_ekleme = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        ornekler = new javax.swing.JMenu();
        ornek1 = new javax.swing.JMenuItem();
        ornek2 = new javax.swing.JMenuItem();
        ornek3 = new javax.swing.JMenuItem();
        ornek4 = new javax.swing.JMenuItem();
        ornek5 = new javax.swing.JMenuItem();
        hakkimizda_button = new javax.swing.JMenu();
        ogrenci_bilgi_button = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Otomata Projesi");

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pars edilecek Regex'i bu kutuya giriniz ");

        regex_alani.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        pars_button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pars_button.setText("Pars Etmek İçin Tıklayınız");
        pars_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pars_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pars edilen Regex (İnfix Hal) aşağıdaki gibidir");

        infix_alani.setEditable(false);
        infix_alani.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        nfa_button.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nfa_button.setText("Parslı İfadeyi NFA'e Dönüştürmek İçin Tıklayınız");
        nfa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfa_buttonActionPerformed(evt);
            }
        });

        jLabel3.setText("Parslı ifadenin NFA hali aşağıdaki gibidir:");

        nfa_alani.setEditable(false);
        nfa_alani.setColumns(20);
        nfa_alani.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        nfa_alani.setRows(5);
        jScrollPane3.setViewportView(nfa_alani);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nfa_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nfa_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        dosya_yolu_ekleme.setText("Dosya Yolu Ekle");
        dosya_yolu_ekleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosya_yolu_eklemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(639, 639, 639)
                .addComponent(dosya_yolu_ekleme))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(regex_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pars_button))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(infix_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(dosya_yolu_ekleme)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(regex_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(pars_button)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(infix_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ornekler.setText("Örnekler");

        ornek1.setText("1. Örnek");
        ornek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornek1ActionPerformed(evt);
            }
        });
        ornekler.add(ornek1);

        ornek2.setText("2. Örnek");
        ornek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornek2ActionPerformed(evt);
            }
        });
        ornekler.add(ornek2);

        ornek3.setText("3. Örnek");
        ornek3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornek3ActionPerformed(evt);
            }
        });
        ornekler.add(ornek3);

        ornek4.setText("4. Örnek");
        ornek4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornek4ActionPerformed(evt);
            }
        });
        ornekler.add(ornek4);

        ornek5.setText("5. Örnek");
        ornek5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ornek5ActionPerformed(evt);
            }
        });
        ornekler.add(ornek5);

        jMenuBar1.add(ornekler);

        hakkimizda_button.setText("Hakkımızda");
        hakkimizda_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakkimizda_buttonActionPerformed(evt);
            }
        });

        ogrenci_bilgi_button.setText("Bilgi");
        ogrenci_bilgi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenci_bilgi_buttonActionPerformed(evt);
            }
        });
        hakkimizda_button.add(ogrenci_bilgi_button);

        jMenuBar1.add(hakkimizda_button);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    ///////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    private void pars_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pars_buttonActionPerformed
        //pars etme butonuna basıldığında RegexToInfıx classından referans üreten ve
        //RegexToInfıx dosyası içindeki pars algoritmasını gerçekleyen kısım
        
        String kullanici_girisi = regex_alani.getText();    //regex_alani isimli Text Area dan alınan yazıyı String e eşitledik
        RegexToInfıx regex1 = new RegexToInfıx(kullanici_girisi);     //RegexToInfıx classına bağlı bir nesne ürettik ve constructoruna bir String verdik
        //üst satırdaki metodla kullanici girisi String imiz RegexToInfıx classına giderek infix hale gelir
        infix_alani.setText(regex1.getRegex());        //RegexToInfıx e gidip pars edilerek(infix olarak) değişen String değerini gui ye yazdırdık
        
        //regex1.reset();                             //regex1 referansını sıfırladık, yoksa hata çıkar
    }//GEN-LAST:event_pars_buttonActionPerformed
    
    
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    private void nfa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfa_buttonActionPerformed
        String parsli_hal = infix_alani.getText(); //infix_alani dan alınan text parslı_hal Stringine aktarılacak 
        
        //InfixToPostfix isimli classın infixToPostFix metodu "parsli_hal" infix Stringini alacak
        //böylece Infix olan "parsli_hal" isimli String postfix olacak
        
        
        InfixToPostfix Infix_referans = new InfixToPostfix();
        String postfix_olan = Infix_referans.infixToPostFix(parsli_hal);
        //InfixToPostfix metodundan çıkan çıktı; postfix_olan isimli String e eşitlendi
        
        
        
        //şimdi , "postfix_olan" isimli String,"PostFixToNFA" classına verilecek
        
        
        PostFixToNFA.NFA nfa10= new PostFixToNFA.NFA();  // "PostFixToNFA" class ındaki static NFA classından obje oluşturuldu
        nfa10=PostFixToNFA.PostFixtonfaa(postfix_olan);  //bu obje yardımıyla PostFixtonfaa fonksiyonuna "postfix_olan" Stringi verildi.
        //böylece "PostFixToNFA" classımız "postfix_olan" Stringimizi almıp NFA e çevirdi
        
        
        try(FileWriter writer5=new FileWriter("nfaSonucu.txt")){
            writer5.write(nfa10.display_to_string());  //"PostFixToNFA" classındaki display_to_string() metodu ile,
                                                       //NFA sonucu "nfaSonucu.txt" isimli dosyaya yazdırıldı
        } catch (IOException ex) {
            System.out.println("dosya oluşturulurken hata oluştu");
        }
        
        
        
        
        
        //Üstte "nfaSonucu.txt" ye aktarılan NFA sonucunun butona basılnca okunmasını sağlayacağız
        
        String NFAsonucu = "";
        try(Scanner scanner = new Scanner(new FileReader("nfaSonucu.txt"))){
            while(scanner.hasNextLine()){
                NFAsonucu += scanner.nextLine() + "\n";
            }
            
        } catch (FileNotFoundException ex) {
            System.out.println("Okunacak dosya bulunamadı");
        }
        
        nfa_alani.setText(NFAsonucu);   //NFA sonucu nfa_alani isimli text area ya yazdırıldı.
        
        
        
        //tekrar nfaSonucu.txt den okuma yapalım
        //ama bu kez graphviz kütüphanesinin  anlayacağı bir formata çevirelim
        
        
        String donusecek = "";
        String donusen = "";
         try(Scanner scanner = new Scanner(new FileReader("nfaSonucu.txt"))){
            while(scanner.hasNextLine()){
                donusecek = scanner.nextLine();
                String[] array = donusecek.split("-->");
                donusen += array[0]+"->"+array[2]+ " [label="+  "\""  + array[1] + "\"" +"]"+ "\n";  
                //S0-->E-->S1
                //s0->s1 [label="E"]
                
            }
            
        } catch (FileNotFoundException ex) {
            System.out.println("Okunacak dosya bulunamadı");
        }
         
         
///////////////////////////////////////////////NFA final state'i bulma
        String ara_satir = "";
        //S0-->E-->S1
        String[] array_f;
        ArrayList<Integer> rakam_liste = new ArrayList<Integer>();
         try(Scanner scanner = new Scanner(new FileReader("nfaSonucu.txt"))){
            while(scanner.hasNextLine()){
                
                ara_satir = scanner.nextLine().replaceAll("S","");   //0-->E-->1
                array_f = ara_satir.split("-->");  
                rakam_liste.add(Integer.valueOf(array_f[2]));
                
            }
            
             
            
        } catch (FileNotFoundException ex) {
            System.out.println("Okunacak dosya bulunamadı");
        }
         
  /////////////////////////////////////////////////////      
        
        




//graphviz e verilecek olan String--->> donusen (bu String  FileWriter ile bir dot dosyasına yazdırılacak)
        
        
        
        String son_durum= "S"+rakam_liste.get(rakam_liste.size()-1); //NFA final state'i bulundu



        //donusen isimli String i "forGraphviz.dot" isimli dot dosyasına yazdırma işlemi
         
        try(FileWriter nfaTodotWriter=new FileWriter("NFAdraw.dot")){
            String bastaki_yazi = "digraph deneme { \n" + "start [shape=point] \n" + "start->S0 \n"
                    + "rankdir=LR \n";
            
            nfaTodotWriter.write(bastaki_yazi);
            
            nfaTodotWriter.write(donusen);
            
            String sondaki_yazi = "\n" + son_durum + " [shape=doublecircle] \n"  + "\n }" ;
            nfaTodotWriter.write(sondaki_yazi);
            
        } catch (IOException ex) {
            System.out.println("dosya oluşturulurken hata oluştu");
        }
  
        //Dot file yazıldı
///////////////////////////////////////////////////////////////////////////////////////
           
        //cmd den okuma işlemleri başlıyor.
   
//////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    
    try
        {
            
            try
            {
                Runtime.getRuntime().exec("cmd.exe /c cd "+  dosya_yolu +" & start cmd.exe /k \"dot -Tpng NFAdraw.dot -o Cikti.png\"");
                //komut satırı açılır ve cmd ye dot dosyasında png ye dönüştürme kodu yazdırılır
                Thread.sleep(2000);
                Runtime.getRuntime().exec("taskkill /f /im cmd.exe");
            }
            catch (Exception e)
            {
                System.out.println("Komut satırında işlem yapılırken bir hata oluştu!");
                e.printStackTrace();
            }
            
          
            
            Thread.sleep(2500);
            
            File f = new File(dosya_yolu+"\\Cikti.png");
            //png dosyasının yolu okundu
            Desktop d = Desktop.getDesktop();
            d.open(f);  //dosya açıldı
            
        } catch (InterruptedException ex) {
            Logger.getLogger(gui1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(gui1.class.getName()).log(Level.SEVERE, null, ex);
        }

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////       
    
        







        
        
        
        
    }//GEN-LAST:event_nfa_buttonActionPerformed

    private void ornek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornek2ActionPerformed
        regex_alani.setText("a(a|b)*b");
    }//GEN-LAST:event_ornek2ActionPerformed

    private void ornek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornek1ActionPerformed
        regex_alani.setText("abb");
    }//GEN-LAST:event_ornek1ActionPerformed

    private void ornek3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornek3ActionPerformed
        regex_alani.setText("(a|b)*abb(a|b)*");
    }//GEN-LAST:event_ornek3ActionPerformed

    private void hakkimizda_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakkimizda_buttonActionPerformed
        
    }//GEN-LAST:event_hakkimizda_buttonActionPerformed

    private void ogrenci_bilgi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenci_bilgi_buttonActionPerformed
        //Hakkimizda isimli Jframe'i çağırma metodu
        Hakkimizda hakkimizda = new Hakkimizda();
        hakkimizda.setVisible(true);
    }//GEN-LAST:event_ogrenci_bilgi_buttonActionPerformed

    private void ornek4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornek4ActionPerformed
        regex_alani.setText("(((ab(a|ba*)*)ab)|ab)ab*a|abba*");
    }//GEN-LAST:event_ornek4ActionPerformed

    private void ornek5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ornek5ActionPerformed
         regex_alani.setText("(((ab(a|ba*)*)ab)|ab)ab*a|abba*(ab*b|ba*)");
    }//GEN-LAST:event_ornek5ActionPerformed

    private void dosya_yolu_eklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosya_yolu_eklemeActionPerformed
        DosyaYoluEkleme dosya_yolu_referans= new DosyaYoluEkleme();
        dosya_yolu_referans.setVisible(true);
        dosya_yolu=dosya_yolu_referans.getKonum();
    }//GEN-LAST:event_dosya_yolu_eklemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dosya_yolu_ekleme;
    private javax.swing.JMenu hakkimizda_button;
    private javax.swing.JTextField infix_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea nfa_alani;
    private javax.swing.JButton nfa_button;
    private javax.swing.JMenuItem ogrenci_bilgi_button;
    private javax.swing.JMenuItem ornek1;
    private javax.swing.JMenuItem ornek2;
    private javax.swing.JMenuItem ornek3;
    private javax.swing.JMenuItem ornek4;
    private javax.swing.JMenuItem ornek5;
    private javax.swing.JMenu ornekler;
    private javax.swing.JButton pars_button;
    private javax.swing.JTextField regex_alani;
    // End of variables declaration//GEN-END:variables
}
